### ISSUE TITLE
[Bug] Convex is not disabled in local development builds

### ISSUE THREAD

**Issue by nathblade16** [EducationalTools/src#436]
### Describe the bug

In a local development build you are missing a .env file so you cannot use convex and it will throw an http error 500, to fix detect a local development build and disable convex

### How could you reproduce this issue?

1. Make a local development build
2. Open it
3. Error 500

### What did you expect to happen?

It loads

### Relevant log output

```shell
Error: Expected string url property for setupConvex
    at setupConvex (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/convex-svelte@0.0.11_convex@1.25.4_react@19.1.0__svelte@5.36.2/node_modules/convex-svelte/dist/client.svelte.js:33:9)
    at Providers (/home/nathblade16/Downloads/edutools/src/src/lib/components/providers.svelte:11:13)
    at $$render_inner (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:72:36)
    at _layout (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:137:3)
    at Root (/home/nathblade16/Downloads/edutools/src/.svelte-kit/generated/root.svelte:61:3)
    at render (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/internal/server/index.js:90:3)
    at Function._render [as render] (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/legacy/legacy-server.js:27:24)
    at render_response (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:192:29)
    at async render_page (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:305:10)
    at async resolve (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/respond.js:501:18)
Error: Expected string url property for setupConvex
    at setupConvex (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/convex-svelte@0.0.11_convex@1.25.4_react@19.1.0__svelte@5.36.2/node_modules/convex-svelte/dist/client.svelte.js:33:9)
    at Providers (/home/nathblade16/Downloads/edutools/src/src/lib/components/providers.svelte:11:13)
    at $$render_inner (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:72:36)
    at _layout (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:137:3)
    at Root (/home/nathblade16/Downloads/edutools/src/.svelte-kit/generated/root.svelte:61:3)
    at render (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/internal/server/index.js:90:3)
    at Function._render [as render] (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/legacy/legacy-server.js:27:24)
    at render_response (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:192:29)
    at async render_page (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:305:10)
    at async resolve (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/respond.js:501:18)
Error: Expected string url property for setupConvex
    at setupConvex (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/convex-svelte@0.0.11_convex@1.25.4_react@19.1.0__svelte@5.36.2/node_modules/convex-svelte/dist/client.svelte.js:33:9)
    at Providers (/home/nathblade16/Downloads/edutools/src/src/lib/components/providers.svelte:11:13)
    at $$render_inner (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:72:36)
    at _layout (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:137:3)
    at Root (/home/nathblade16/Downloads/edutools/src/.svelte-kit/generated/root.svelte:61:3)
    at render (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/internal/server/index.js:90:3)
    at Function._render [as render] (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/legacy/legacy-server.js:27:24)
    at render_response (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:192:29)
    at async render_page (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:305:10)
    at async resolve (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/respond.js:501:18)
Error: Expected string url property for setupConvex
    at setupConvex (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/convex-svelte@0.0.11_convex@1.25.4_react@19.1.0__svelte@5.36.2/node_modules/convex-svelte/dist/client.svelte.js:33:9)
    at Providers (/home/nathblade16/Downloads/edutools/src/src/lib/components/providers.svelte:11:13)
    at $$render_inner (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:72:36)
    at _layout (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:137:3)
    at Root (/home/nathblade16/Downloads/edutools/src/.svelte-kit/generated/root.svelte:61:3)
    at render (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/internal/server/index.js:90:3)
    at Function._render [as render] (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/legacy/legacy-server.js:27:24)
    at render_response (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:192:29)
    at async respond_with_error (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:86:10)
    at async render_page (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:324:10)
Error: Expected string url property for setupConvex
    at setupConvex (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/convex-svelte@0.0.11_convex@1.25.4_react@19.1.0__svelte@5.36.2/node_modules/convex-svelte/dist/client.svelte.js:33:9)
    at Providers (/home/nathblade16/Downloads/edutools/src/src/lib/components/providers.svelte:11:13)
    at $$render_inner (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:72:36)
    at _layout (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:137:3)
    at Root (/home/nathblade16/Downloads/edutools/src/.svelte-kit/generated/root.svelte:61:3)
    at render (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/internal/server/index.js:90:3)
    at Function._render [as render] (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/legacy/legacy-server.js:27:24)
    at render_response (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:192:29)
    at async respond_with_error (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:86:10)
    at async render_page (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:324:10)
Error: Expected string url property for setupConvex
    at setupConvex (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/convex-svelte@0.0.11_convex@1.25.4_react@19.1.0__svelte@5.36.2/node_modules/convex-svelte/dist/client.svelte.js:33:9)
    at Providers (/home/nathblade16/Downloads/edutools/src/src/lib/components/providers.svelte:11:13)
    at $$render_inner (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:72:36)
    at _layout (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:137:3)
    at Root (/home/nathblade16/Downloads/edutools/src/.svelte-kit/generated/root.svelte:61:3)
    at render (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/internal/server/index.js:90:3)
    at Function._render [as render] (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/legacy/legacy-server.js:27:24)
    at render_response (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:192:29)
    at async respond_with_error (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:86:10)
    at async render_page (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:324:10)
Error: Expected string url property for setupConvex
    at setupConvex (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/convex-svelte@0.0.11_convex@1.25.4_react@19.1.0__svelte@5.36.2/node_modules/convex-svelte/dist/client.svelte.js:33:9)
    at Providers (/home/nathblade16/Downloads/edutools/src/src/lib/components/providers.svelte:11:13)
    at $$render_inner (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:72:36)
    at _layout (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:137:3)
    at Root (/home/nathblade16/Downloads/edutools/src/.svelte-kit/generated/root.svelte:61:3)
    at render (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/internal/server/index.js:90:3)
    at Function._render [as render] (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/legacy/legacy-server.js:27:24)
    at render_response (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:192:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async render_page (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:305:10)
Error: Expected string url property for setupConvex
    at setupConvex (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/convex-svelte@0.0.11_convex@1.25.4_react@19.1.0__svelte@5.36.2/node_modules/convex-svelte/dist/client.svelte.js:33:9)
    at Providers (/home/nathblade16/Downloads/edutools/src/src/lib/components/providers.svelte:11:13)
    at $$render_inner (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:72:36)
    at _layout (/home/nathblade16/Downloads/edutools/src/src/routes/+layout.svelte:137:3)
    at Root (/home/nathblade16/Downloads/edutools/src/.svelte-kit/generated/root.svelte:61:3)
    at render (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/internal/server/index.js:90:3)
    at Function._render [as render] (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/svelte@5.36.2/node_modules/svelte/src/legacy/legacy-server.js:27:24)
    at render_response (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:192:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async respond_with_error (/home/nathblade16/Downloads/edutools/src/node_modules/.pnpm/@sveltejs+kit@2.24.0_@sveltejs+vite-plugin-svelte@5.1.1_svelte@5.36.2_vite@6.3.5_@types_109b81d8eb61b9907075f9e231009927/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:86:10)
```

### Browser

Firefox/Gecko based (Firefox, Zen, Librewolf, etc.)

### Operating System

Linux

**Comment by ingoau** [comment]
Fixed

**Comment by nathblade16** [comment]
the issue still appears to be present after a fresh download and build

**Comment by ingoau** [comment]
I'll investigate now

**Comment by ingoau** [comment]
Can you checkout `convex-fixes` and try there?
